version: 2

workflows:
  version: 2
  default:
    jobs:
      - build-elcapitan
      - build-sierra

step-library:
  - &install-brew-deps
      run:
        name: Install Dependencies via Homebrew
        command: |
          brew update
          brew uninstall libtool
          brew install libtool
          brew install gengetopt help2man

  - &compile
      run:
        name: Compile OpenSC
        command: |
          MacOSX/build

  - &test
      run:
        name: Run Tests
        command: |
          make check
          make dist

jobs:
  build-elcapitan:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - *install-brew-deps
      - *compile
      - *test

  build-sierra:
    macos:
      xcode: "8.0"
    steps:
      - checkout
      - *install-brew-deps
      - *compile
      - *test
