version: 2

workflows:
  version: 2
  default:
    jobs:
      - build-elcapitan
      - build-sierra

jobs:
  build-elcapitan:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: MacOSX/build

  build-sierra:
    macos:
      xcode: "8.0"
    steps:
      - checkout
      - run: MacOSX/build
