version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Build
          command: |
            MacOSX/build

workflows:
  version: 2
  build:
    jobs:
      - build
